version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: demo-backend
    ports:
      - "4000:4000"  
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/grocerydb
    depends_on:
      - mongo
    networks:
      - demo-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: demo-frontend
    ports:
      - "3000:5173"   # frontend served on localhost:3000 (if nginx build) or adjust if vite
    depends_on:
      - backend
    networks:
      - demo-network

  mongo:
    image: mongo:7
    container_name: demo-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - demo-network

volumes:
  mongo_data:

networks:
  demo-network:
    driver: bridge
